### PR TITLE
WIP - 439 issue mixins classes

### PR DESCRIPTION
**Pull request by novellac**
Looking for feedback on the creation of mixins folder. Relates to issue #439

### CODE REVIEW

**Comment by pjsier** [comment]
This looks great to me! Just ran it locally and it seems to work. There might be some linting errors, but otherwise is it ready?

**Comment by novellac** [comment]
Hah yeah those E501 are the bane of my existence sometimes! Should I get those shorter, or is it ok?

**Comment by pjsier** [comment]
Actually, I was wrong. The lint check is passing because we're ignoring E501, so this should be good to go

**Comment by bonfirefan** [comment]
Tests out locally for me! Merging in.

**Pull request merged**
