### PR TITLE
WIP - 468 spider det city planning

### PR DESCRIPTION
**Pull request by novellac**
First pass at Detroit City Planning Commission

### CODE REVIEW

**Comment by novellac** [comment]
References issue #468

**Comment by pjsier** [comment]
It looks like this is branched off of #463 instead of master so it's including all of the changes from that PR too. Could you update this to only include changes related to the city planning spider? I'm happy to clarify anything if you have any questions on that

**Comment by novellac** [comment]
Created a PR #480 which should replace this PR.

**Comment by novellac** [comment]
Closed in favor of #480

**Pull request closed without merging**
