### PR TITLE
Update CPS desc

### PR DESCRIPTION
**Pull request by ckwms63**

### CODE REVIEW

**Comment by bonfirefan** [comment]
This looks good! Thanks @ckwms63

**Comment by diaholliday** [comment]
@bonfirefan this issue was closed but has it been merged? i'm looking at upcoming CPS board meetings in Airtable and they all still say N/A, not sure why.

**Comment by bonfirefan** [comment]
@diaholliday that's odd, it seems to populate with descriptions in my local outputs when I crawl `chi_schools`. The tests should also prevent the spider from crawling without returning the description. Is it not making it to Airtable somehow? Maybe there are no new meetings since last week when we merged this in? @pjsier sees that the spider hasn't run in deployment since April 5th according to the dashboard, so maybe that's the answer.

**Comment by diaholliday** [comment]
Yeah i was thinking it could be because the spider hasn't run since the 5th. Is there a way to make it run now to test it?

**Comment by bonfirefan** [comment]
Addresses #275 
@diaholliday I think that @jim proposed disabling the geocoder pipeline, which means we'll at least be able to populate new events. Not sure what the schedule is on that

**Comment by jim** [comment]
I disabled the geocoding pipeline last night, so events should be showing up again.

**Pull request merged**
