### PR TITLE
Add chi_ssa_18

### PR DESCRIPTION
**Pull request by AmiMappy**

### CODE REVIEW

**Comment by AmiMappy** [comment]
Would appreciate any changes

**Comment by pjsier** [comment]
@AmiMappy thanks for the PR! It looks like it's missing the test files generated by `scrapy genspider`. I can take a closer look if you add those here and implement the tests

**Comment by AmiMappy** [comment]
[files.zip](https://github.com/City-Bureau/city-scrapers/files/3695822/files.zip)
Did you mean these?

**Comment by AmiMappy** [comment]
I ran the test (test_chi_ssa_18.py) from cmd, and no output was generated.

**Comment by AmiMappy** [comment]
test_chi_ssa_18 output
Is this ok?

**Comment by AmiMappy** [comment]
'Add chi_ssa' happened by mistake

**Comment by AmiMappy** [comment]
'Add test files for chi_ssa' happened by mistake

**Comment by pjsier** [comment]
Thanks! Those are the files we're looking for. Now you just need to implement the tests so that they pass and verify the data the scraper should be pulling and also run the linting checks. I can take a closer look once the Travis CI build passes

**Comment by AmiMappy** [comment]
When I saw the travis build results:-
       FileNotFoundError: [Errno 2] No such file or directory: '/home/travis/build/City-Bureau/city- 
       scrapers/files/chi_ssa_18.html'
But when I ran pytest locally, it only gave errors about other test.py files and a few json files.

**Pull request closed without merging**
