### PR TITLE
Update long name and descrip of chi_city_college spider.

### PR DESCRIPTION
**Pull request by novellac**
Based on issue #275

### CODE REVIEW

**Comment by novellac** [comment]
I think this is good to go - note that there were no tests for the description, so only the spider has changed.

**Comment by r-wei** [comment]
Ah, thanks for catching that, @novellac. Could you add a test for the new description on this pull request? Then we'll merge it in.

**Comment by novellac** [comment]
Yes I'll try to add a test today.

**Comment by novellac** [comment]
Chi city colleges tests seem to have passed. @r-wei is there anything more I need to do?

**Comment by r-wei** [comment]
Looks good to me, thanks!

**Pull request merged**
