### PR TITLE
Creating a prerequisites file

### PR DESCRIPTION
**Pull request by bonfirefan**
Adding some additional resources for a first-time development environment setup, with @ckwms63 's help.

### CODE REVIEW

**Comment by bonfirefan** [comment]
@r-wei I think I'll merge this in EOD if we don't see any mis-informations in the file as it would mainly be fore first-time coders who need a bit a catchup reference

**Comment by r-wei** [comment]
@bonfirefan looks good to me, thanks for doing this :) I'm cool with iterating on this as Caroline suggested. Maybe also add a link from the README to this prerequisites page?

**Comment by r-wei** [comment]
Another suggestion from @diaholliday -- maybe call this something like "additional resources" or "background materials"? so "prerequisites" doesn't suggest to people that it's something they have to be an expert at before joining

**Comment by bonfirefan** [comment]
OK, I'll merge this in and we'll continue to edit this! What @easherma [mentioned with pipenv](https://github.com/City-Bureau/city-scrapers/issues/62#issuecomment-379005737) (which would be greaaaaat!) will hopefully change the Windows warning. Emmanuel said he'd give some feedback, too.

**Pull request merged**
