### PR TITLE
Cook County Housing Authority spider #192

### PR DESCRIPTION
**Pull request by cherdeman**

### CODE REVIEW

**Comment by r-wei** [comment]
Yep, you can use [curl](http://www.compciv.org/recipes/cli/downloading-with-curl/), and save the file in the [city-scrapers/test/files folder](https://github.com/City-Bureau/city-scrapers/tree/master/tests/files).

**Comment by cherdeman** [comment]
Followup, presumably I'll need to aggregate the html of each individual event page into one file?

**Comment by r-wei** [comment]
@cherdeman , you could just download one of the individual event pages using curl and test the [_parse_event function](https://github.com/City-Bureau/city-scrapers/pull/339/files#diff-f4f4e6d144d4b9009ffee4f32c8b3c2bR40). The [test for cook_pubhealth](https://github.com/City-Bureau/city-scrapers/blob/master/tests/test_cook_pubhealth.py) is an example of testing against a single event page.

**Comment by cherdeman** [comment]
@r-wei Got it! I added tests and the static file, let me know if you need any updates.

**Comment by r-wei** [comment]
Hey @cherdeman , can you make sure all the functions (individual tests) in test_cook_housingauthority.py and test_chi_library.py have unique names? For example, if you have multiple tests called `test_allday`, pytest only runs one of them. Other than that, looks good!

**Comment by cherdeman** [comment]
Ah my bad @r-wei! I think I caught all of them this time, let me know if you notice any more.

**Comment by r-wei** [comment]
resolves #340 #192

**Pull request merged**
