### PR TITLE
471 det_land_bank first pass

### PR DESCRIPTION
**Pull request by novellac**
Work in progress for det_land_bank
References #471

### CODE REVIEW

**Comment by novellac** [comment]
Ok I think this is ready for review.

**Comment by pjsier** [comment]
This looks good to me. One thing we haven't been super strict about that could be helpful here is using consistent camel-casing in class names, making this `DetLandBankSpider`. We'll need to fix that in existing spiders and our template, but it would be nice to have that in new spiders. Otherwise I think this is ready to merge

**Comment by novellac** [comment]
I have just been creating the spiders as per https://github.com/City-Bureau/city-scrapers/blob/master/docs/03_contribute.md

**Comment by novellac** [comment]
Renamed to spider and all spidery things to use camel case.

**Pull request merged**
