### PR TITLE
WIP: 0318 spider cps community action council

### PR DESCRIPTION
**Pull request by brettvanderwerff**
This is a rough start to the #318  CPS community action council spider. I made the pull request because of issue #328, which seemed to look for new contributors to open pull requests early for development visibility. I am pretty new so a lot of this is in the very, very early stages and not really operational.

### CODE REVIEW

**Comment by jim** [comment]
Hi @brettvanderwerff! Thanks for opening this PR. This way we know that you're working on this scraper and can try to provide whatever support you need. Please let us know on this PR or in Slack if you have any questions and we'll do our best to answer them!

**Comment by r-wei** [comment]
Hey Brett, thanks for reaching out. Here are some responses to the problems:

1. I’m not seeing any strange encodings in the scraped data or errors when I run this spider. Maybe you’ve already fixed this? You can also use the [strip()](https://docs.python.org/3/library/stdtypes.html#str.strip) method to remove whitespace on the ends of strings.

2. The dates look correct to me. Since the events are recurring, would you be able to write code to generate all the events through the end of 2018? So for the Austin one, this would be: May 8, June 12, July 10, etc--all the way through December. I know that the [ward night spider](https://github.com/City-Bureau/city-scrapers/blob/master/city_scrapers/spiders/ward_night.py) does this, and maybe @jim has hints on how to do easily. But if you feel it's too much work, we can merge this in, and open another issue to refactor this spider to get all the recurrences.

2 and 3. Humboldt Park — East: Let’s leave this event off for now. I’m not seeing these events listed in Humboldt Park East’s website either, so we can have someone reach out to Carl Hurdlik as a non-coding task.

4. It looks good. The comments are helpful. :)

**Comment by brettvanderwerff** [comment]
I get the weird encoding when I view the locally outputted data I see things like "Humboldt Park â€“ East" instead of "Humboldt Park East", maybe it is just my environment though?  If you don;t see it I'm not going to worry about it. 

I will try to generate all the events through the end of 2018 and will look at  the ward night spider for a better idea of what you are talking about. 

I'll try to write in a mechanism to skip Humboldt Park — East.

I should be able to get tho these in the next few days I hope. 

Thanks for the review.

**Comment by brettvanderwerff** [comment]
This spider is basically done with one exception:

I addressed most of @r-wei's comments, the last thing is to write code to generate all the events through the end of 2018. Could someone shine more detail on what the expected output format for this would be?

I tried looking at the output of the wardnight spider that was suggested as an example  by running "scrapy crawl ward_night" in the terminal, which give me a csv like it should  but unfortunately the csv is empty so I can't see the output you are shooting for.  Please let me know thanks.

**Comment by r-wei** [comment]
Hey @brettvanderwerff , generating all the events means creating a bunch of scraped items (dictionaries) with identical data except for the start_time. For some context, we're feeding the scraped items into a database where each row is a different event. Does that make sense?

Thanks for the tip about the ward night spider. I'll take a look into that.

**Comment by brettvanderwerff** [comment]
@r-wei Thanks for the response, I think I can see how that would be done without changing the spider too much. I'll start work on that.

**Comment by r-wei** [comment]
looks good, thanks @brettvanderwerff

**Pull request merged**
