### PR TITLE
435 wayne_public_services new spider

### PR DESCRIPTION
**Pull request by novellac**
This spider is same as spider #419 (the tests are slightly different, of course).

### CODE REVIEW

**Comment by r-wei** [comment]
@novellac , if these spiders are the same, is there a way we can write one wayne_county spider class and then have each commission spider inherit from it? It looks like there will be a bunch of these, and it would be better for maintenance not to have so many copies of the same code.

**Comment by novellac** [comment]
I'd like to try to run the new spider on the rest of the ticket group - I'm hoping you're right and I can use one wayne_county_commission spider class.

**Comment by novellac** [comment]
This spider will fail CI checks until the mixins folder is committed, I think.

**Comment by novellac** [comment]
Ready for review

**Comment by pjsier** [comment]
Replaced by #459

**Pull request closed without merging**
