### PR TITLE
renamed spider and test files, address PR  #288 and issue #257

### PR DESCRIPTION
**Pull request by cherdeman**
I may have done the branching wrong on this but hopefully the pull works!

### CODE REVIEW

**Comment by bonfirefan** [comment]
Hey @cherdeman, thanks for writing out the tests and creating the test file! [Travis does an additional check ](https://github.com/City-Bureau/city-scrapers/blob/master/travis/validate_spiders.sh) on new spiders[ to validate their output](https://github.com/City-Bureau/city-scrapers/blob/master/tasks.py#L161), and in the process calls the spider with `scrapy crawl`. It looks like the crawler itself is not in a working state and breaks when parsing the name of the item. When you run `scrapy crawl chi_water --loglevel=ERROR` you should be able to replicate the issue.

**Comment by bonfirefan** [comment]
So, it looks we're returning a tuple from legistar - the first item is the dictionary we want, the second one a Legistar class object. If you set `item = item[0]` in the events `for` loop, it should hopefully resolve the issue.

**Comment by cherdeman** [comment]
Thanks @bonfirefan! updated the test file to match and I think it's good to go.

**Comment by bonfirefan** [comment]
This looks ready to merge in! Pinging @diaholliday  - the only thing I think we should clarify is that the spider currently skips Water Reclamation events with no meeting time. When you [look at the events](https://mwrd.legistar.com/Calendar.aspx) you can see that those sessions are usually "Study Sessions" presenting different committee processes (Budget, Procurement) or findings/discussion (Ethics - having an inspector general, Engineer - managing organic material). These are usually scheduled "after the regular board meeting" and seem to vary in actual start time from 12pm-1:30pm. Given that the Board meeting re-convenes as the Committee of the Whole (listed as two separate events) on the same day, then re-convenes for these study sessions, would we be ok including these study sessions with a placeholder time of the board time + 15 minutes, or no time at all?

**Comment by bonfirefan** [comment]
Actually, for these Study Sessions, it looks as if the date is not being captured at all, though it is being converted and the event itself gets scraped. @cherdeman Could we keep the start date and set the time to midnight if there is no time?

**Comment by cherdeman** [comment]
@bonfirefan I think that should do it, let me know if there are still remaining issues with the time.

**Pull request merged**
